INSERT INTO department (name)
VALUES ('Engeneering'),
       ('Sales'),
       ('Finance'),
       ('Development');

INSERT INTO roles (title, salary, department_id)
VALUES ('Supervisor', 150000, 1),
       ('Team_Lead', 100000, 2),
       ('Senior_Employee', 85000, 3),
       ('General_Employee', 60000, 4);

INSERT INTO employee (first_name, last_name, role_id, manager_id)
VALUES ('Mike', 'Willice', 1, NULL),
       ('Joe', 'Connors', 1, NULL),
       ('Sally', 'Fields', 1, NULL),
       ('Sherri', 'Brown', 1, NULL),
       ('Luis', 'Garcia', 1, NULL),
       ('Ralph', 'Machio', 2, 1),
       ('Susan', 'McCloud', 2, 1),
       ('Manny', 'Longbottom', 2, 2),
       ('Alvin', 'Addams', 2, 2),
       ('Richard', 'Smith', 2, 3),
       ('Lucas', 'Pacqueta', 2, 3),
       ('Samantha', 'Wilburn', 2, 4),
       ('Sandra', 'McGregor', 2, 4),
       ('Simon', 'Pegg', 2, 5),
       ('Michael', 'Myers', 2, 5),
       ('Bruce', 'Campbell', 3, 1),
       ('Dee', 'Snyder', 3, 1),
       ('Gerry', 'Dee', 3, 2),
       ('Alice', 'Wonderland', 3, 2),
       ('Jimmy', 'Cricket', 3, 3),
       ('Aldous', 'Dumbledore', 3, 3),
       ('Barbara', 'Walters', 3, 4),
       ('Mister', 'White', 3, 4),
       ('Vince', 'McMahon', 3, 5),
       ('Gordon', 'Ramsay', 3, 5),
       ('Vicky', 'Flanders', 4, 1),
       ('Michelle', 'Obama', 4, 1),
       ('Crystal', 'Sounds', 4, 1),
       ('Rizzy', 'Bizzy', 4, 1),
       ('Leon', 'Kennedy', 4, 2),
       ('Claire', 'Redfield', 4, 2),
       ('Jill', 'Valentine', 4, 2),
       ('Barry', 'Burton', 4, 2),
       ('Silver', 'Surfer', 4, 3),
       ('Barry', 'Allen', 4, 3),
       ('Katelyn', 'Frost', 4, 3),
       ('Bilbo', 'Baggins', 4, 3),
       ('Gandalf', 'TheWise', 4, 4),
       ('Freddy', 'Prince', 4, 4),
       ('Mireal', 'Smothers', 4, 4),
       ('Minnie', 'Driver', 4, 4),
       ('Ronald', 'McDonald', 4, 5),
       ('Sandy', 'Whirl', 4, 5),
       ('Annie', 'Oakley', 4, 5),
       ('Willey', 'Coyote', 4, 5),
       ('Happy', 'Feet', 4, 5);